config/routes.rb
Rails.application.routes.draw do
  post "/graphql", to: "graphql#execute"
  root to: 'visitors#index'
  devise_for :users
  resources :users
  resources :answers
  resources :questions
  resources :exams do
    get :exam_summary, :on => :collection
  end

end

app/models/answer.rb
class Answer < ApplicationRecord
    belongs_to :user
    belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chapter.rb
class Chapter < ApplicationRecord
    has_many :questions
    belongs_to :topic
end

app/models/easy_question.rb
class EasyQuestion < Question
end

app/models/exam.rb
class Exam < ApplicationRecord
    has_many :subjects
    has_and_belongs_to_many :users
    
end

app/models/hard_question.rb
class HardQuestion < Question
end

app/models/jw_token.rb
class JwToken < ApplicationRecord
    belongs_to :user
    validates :user_id, presence: true
end

app/models/medium_question.rb
class MediumQuestion < Question
end

app/models/option.rb
class Option < ApplicationRecord
    belongs_to :question
end

app/models/question.rb
class Question < ApplicationRecord
    has_many :answers
    belongs_to :chapter
    has_many :options
    belongs_to :correct_option, class_name: 'Option', foreign_key: :correct_option_id, optional: true

    def exam
        chapter.topic.subject.exam
    end

    def url
        question_url(self, format: :json)
    end
end

app/models/subject.rb
class Subject < ApplicationRecord
    has_many :topics
    belongs_to :exam
end

app/models/topic.rb
class Topic < ApplicationRecord
    has_many :chapters
    belongs_to :subject
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :answers
  has_and_belongs_to_many :exams
  # validates :email, email: true
  # validates :email, uniqueness: { scope: :session, message: "cannot be used more than one time" }
  after_commit :create_jw_token, on: :create
  has_one :jw_token

  def create_jw_token
    JwtService.new(user: self).build!
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_answer, only: [:show, :edit, :update, :destroy]

  # GET /answers
  # GET /answers.json
  def index
    @answers = Answer.all
  end

  # GET /answers/1
  # GET /answers/1.json
  def show
  end

  # GET /answers/new
  def new
    @answer = Answer.new
  end

  # GET /answers/1/edit
  def edit
  end

  # POST /answers
  # POST /answers.json
  def create
    #answer_params will contain question_id, user_id and option_id ( if option_id is nil question is skipped)
    answer_params = {
      question_id: params[:question_id],
      user_id: current_user.id
    }
    @answer = Answer.find_or_initialize_by(answer_params)
    @answer.option_id = params[:option_id]
    respond_to do |format|
      if @answer.save
        format.html { redirect_to @answer, notice: 'Answer was successfully saved.' }
        format.json { render :show, status: :created, location: @answer }
      else
        format.html { render :new }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /answers/1
  # PATCH/PUT /answers/1.json
  def update
    respond_to do |format|
      if @answer.update(answer_params)
        format.html { redirect_to @answer, notice: 'Answer was successfully updated.' }
        format.json { render :show, status: :ok, location: @answer }
      else
        format.html { render :edit }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
    @answer.destroy
    respond_to do |format|
      format.html { redirect_to answers_url, notice: 'Answer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = Answer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def answer_params
      params.fetch(:answer, {})
    end
end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
  before_action :set_chapter, only: [:show, :edit, :update, :destroy]

  # GET /chapters
  # GET /chapters.json
  def index
    @chapters = Chapter.all
  end

  # GET /chapters/1
  # GET /chapters/1.json
  def show
  end

  # GET /chapters/new
  def new
    @chapter = Chapter.new
  end

  # GET /chapters/1/edit
  def edit
  end

  # POST /chapters
  # POST /chapters.json
  def create
    @chapter = Chapter.new(chapter_params)

    respond_to do |format|
      if @chapter.save
        format.html { redirect_to @chapter, notice: 'Chapter was successfully created.' }
        format.json { render :show, status: :created, location: @chapter }
      else
        format.html { render :new }
        format.json { render json: @chapter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chapters/1
  # PATCH/PUT /chapters/1.json
  def update
    respond_to do |format|
      if @chapter.update(chapter_params)
        format.html { redirect_to @chapter, notice: 'Chapter was successfully updated.' }
        format.json { render :show, status: :ok, location: @chapter }
      else
        format.html { render :edit }
        format.json { render json: @chapter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chapters/1
  # DELETE /chapters/1.json
  def destroy
    @chapter.destroy
    respond_to do |format|
      format.html { redirect_to chapters_url, notice: 'Chapter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chapter
      @chapter = Chapter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chapter_params
      params.fetch(:chapter, {})
    end
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
  include Questionable
  before_action :authenticate_user!

  def index
    @exams = Exam.all
  end

  def show
    @exam = Exam.find(params[:id])
  end

  def exam_summary
    begin
      @from = params[:from].to_s.capitalize+" ID"
      @summaries = exam_summary_builder(params[:from])
    rescue
      @summaries = []
    end
    respond_to do |format|
      format.html {}
      format.json {}
    end
  end
  
end
  

app/controllers/graphql_controller.rb
class GraphqlController < ApplicationController
  def execute
    variables = ensure_hash(params[:variables])
    query = params[:query]
    operation_name = params[:operationName]
    context = {
      auth_token: request.env['HTTP_AUTHORIZATION']
    }
    result = HardSchema.execute(query, variables: variables, context: context, operation_name: operation_name)
    render json: result
  rescue => e
    raise e unless Rails.env.development?
    handle_error_in_development e
  end

  private

  # Handle form data, JSON body, or a blank value
  def ensure_hash(ambiguous_param)
    case ambiguous_param
    when String
      if ambiguous_param.present?
        ensure_hash(JSON.parse(ambiguous_param))
      else
        {}
      end
    when Hash, ActionController::Parameters
      ambiguous_param
    when nil
      {}
    else
      raise ArgumentError, "Unexpected parameter: #{ambiguous_param}"
    end
  end

  def handle_error_in_development(e)
    logger.error e.message
    logger.error e.backtrace.join("\n")

    render json: { error: { message: e.message, backtrace: e.backtrace }, data: {} }, status: 500
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to root_path, :alert => "Access denied."
    end
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController

    def index
        @user = current_user
        if !user_signed_in?
            redirect_to new_user_session_path
        else
            redirect_to questions_path(id: rand(1..9), name: ['subject','topic','chapter'].sample)
        end
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/answers/_form.html.erb
<%= form_with(model: answer, local: true) do |form| %>
  <% if answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
      <% answer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/answers/edit.html.erb
<h1>Editing Answer</h1>

<%= render 'form', answer: @answer %>

<%= link_to 'Show', @answer %> |
<%= link_to 'Back', answers_path %>

app/views/answers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Answers</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @answers.each do |answer| %>
      <tr>
        <td><%= link_to 'Show', answer %></td>
        <td><%= link_to 'Edit', edit_answer_path(answer) %></td>
        <td><%= link_to 'Destroy', answer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Answer', new_answer_path %>

app/views/answers/new.html.erb
<h1>New Answer</h1>

<%= render 'form', answer: @answer %>

<%= link_to 'Back', answers_path %>

app/views/answers/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_answer_path(@answer) %> |
<%= link_to 'Back', answers_path %>

app/views/chapters/_form.html.erb
<%= form_with(model: chapter, local: true) do |form| %>
  <% if chapter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(chapter.errors.count, "error") %> prohibited this chapter from being saved:</h2>

      <ul>
      <% chapter.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/chapters/edit.html.erb
<h1>Editing Chapter</h1>

<%= render 'form', chapter: @chapter %>

<%= link_to 'Show', @chapter %> |
<%= link_to 'Back', chapters_path %>

app/views/chapters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Chapters</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @chapters.each do |chapter| %>
      <tr>
        <td><%= link_to 'Show', chapter %></td>
        <td><%= link_to 'Edit', edit_chapter_path(chapter) %></td>
        <td><%= link_to 'Destroy', chapter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Chapter', new_chapter_path %>

app/views/chapters/new.html.erb
<h1>New Chapter</h1>

<%= render 'form', chapter: @chapter %>

<%= link_to 'Back', chapters_path %>

app/views/chapters/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_chapter_path(@chapter) %> |
<%= link_to 'Back', chapters_path %>